name: "build"
on:
  schedule:
    # Run weekly on Saturday at midnight PT (3am ET / 8am UTC)
    - cron: "0 8 * * 6"
  push:
    branches:
      - "master"
  pull_request:
  workflow_dispatch:
concurrency:
  group: build-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build-dependencies:
    name: Build the FlexFlow dependencies
    strategy:
      matrix:
        os: [ubuntu-20.04]
        cuda_version:
          [
            "10.1.243"
          ]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: |
          echo "Free space:"
          df -h